apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi.name" . }}-envars
data:
  .env: |-
  {{- range $key, $value := .Values.envVars }}
  {{ $key | indent 2 }}={{ $value | quote }}
  {{- end }}
